### ISSUE TITLE
Exception in thread "main" java.lang.IllegalArgumentException: URI is not hierarchical

### ISSUE THREAD

**Issue by mingodad** [jaimegarza/syntax#26]
When trying to use the this project I'm getting this error:
```
java -jar syntax-4.2.0.jar -l java -v -g syntax.sy 
Exception in thread "main" java.lang.IllegalArgumentException: URI is not hierarchical
	at java.io.File.<init>(File.java:418)
	at me.jaimegarza.syntax.env.Environment.setReportTemplate(Environment.java:493)
	at me.jaimegarza.syntax.env.Environment.parse(Environment.java:223)
	at me.jaimegarza.syntax.env.Environment.<init>(Environment.java:158)
	at me.jaimegarza.syntax.Syntax.main(Syntax.java:156)
```

**Comment by mingodad** [comment]
This seems to fix the problem and I could get it to work:
File `me.jaimegarza.syntax.env.Environment`:
```
   private void setReportTemplate() throws CommandLineParseException {
     URL url = Thread.currentThread().getContextClassLoader().getResource(REPORT_TEMPLATE);
     if (url == null) {
       throw new CommandLineParseException("filename " + REPORT_TEMPLATE + " not found in the class path");
     }
-    reportTemplateFile = new File(URI.create(url.toString()));
-    try {
-      reportTemplate = new BufferedReader(openFileForRead(reportTemplateFile));
-    } catch (IOException e) {
-      throw new CommandLineParseException("Cannot open report template file " + REPORT_TEMPLATE);
-    }
+    //reportTemplateFile = new File(URI.create(url.toString()));
+    //try {
+      reportTemplate = new BufferedReader(new InputStreamReader(Thread.currentThread().getContextClassLoader().getResourceAsStream(REPORT_TEMPLATE)));
+    //} catch (IOException e) {
+    //  throw new CommandLineParseException("Cannot open report template file " + REPORT_TEMPLATE);
+    //}
   }
```

**Comment by mingodad** [comment]
I've just added the `syntax.sy` grammar to https://mingodad.github.io/parsertl-playground/playground/ (select "Jaime Garza Syntax parser` from `Examples` then click `Parse` to see a parse tree for the content in `Input source`).

Also generated this `EBNF` to generate a railroad diagram for the grammar:
```
//
// Copy and paste this at
//      (IPV6) https://www.bottlecaps.de/rr/ui
//      (IPV4) https://rr.red-dove.com/ui
// in the 'Edit Grammar' tab then click the 'View Diagram' tab.
//

Descriptor::=
	  Declarations SectionMarker Productions Actions
	| SectionMarker Productions Actions

SectionMarker::=
	  MARK

Actions::=
	  /*%empty*/
	| MARK ADITIONAL_CODE

Declarations::=
	  Declarations Declaration
	| Declaration

Declaration::=
	  ';'
	| START TOKEN
	| LEXCODE TOKEN
	| TYPE TYPENAME NonTerminals
	| DECLARE TYPENAME
	| NAME TokenNames
	| UNION
	| Precedence Definition
	| LEXER Equals TOKEN
	| GROUP TOKEN ':' TOKEN GroupTokens
	| PROGRAM_DECLARATIONS

Precedence::=
	  TERM
	| LEFT
	| RIGHT
	| BINARY
	| ERRDEF

NonTerminals::=
	  NonTerminals ',' TOKEN
	| TOKEN

TokenNames::=
	  TokenNames ',' Name
	| Name

Name::=
	  TOKEN ':' TOKEN

GroupTokens::=
	  GroupTokens ',' GroupToken
	| GroupToken

GroupToken::=
	  TOKEN

Definition::=
	  Type Tokens

Type::=
	  TYPENAME
	| /*%empty*/

Tokens::=
	  Tokens ',' Token
	| Token

Token::=
	  TokenDef LexicAction

TokenDef::=
	  TOKEN Number TokenName

Number::=
	  NUM
	| /*%empty*/

TokenName::=
	  ':' TOKEN
	| /*%empty*/

LexicAction::=
	  Equals TOKEN
	| RStart RExp REnd
	| RStart RExp REnd REquals TOKEN
	| /*%empty*/

REquals::=
	  '='
	| '[' TOKEN ']' '='

Equals::=
	  '='
	| '[' TOKEN ']' '='

RStart::=
	  '/' TOKEN

REnd::=
	  '/' TOKEN

RExp::=
	  RegExp

RegExp::=
	  RegExp '|' Concatenation
	| Concatenation

Concatenation::=
	  Concatenation UnaryRegex
	| UnaryRegex

UnaryRegex::=
	  BasicElement '*'
	| BasicElement '+'
	| BasicElement '?'
	| BasicElement

BasicElement::=
	  '(' RegExp ')'
	| CHAR
	| '[' CHARACTER_CLASS ']'
	| '.'

Productions::=
	  Productions TOKEN ':' Rules ';'
	| TOKEN ':' Rules ';'

Rules::=
	  Rules '|' GrammarRule
	| GrammarRule

GrammarRule::=
	  Rule
	| /*%empty*/

Rule::=
	  Rule Symbol
	| Symbol

Symbol::=
	  TOKEN
	| PREC TOKEN
	| RULE_ACTION

//Tokens

MARK ::= "%%"
BINARY ::= "%binary"
BINARY ::= "%nonassoc"
DECLARE::= "%declare"
ERRDEF ::= "%error"
GROUP ::= "%group"
LEFT ::= "%left"
LEXER ::= "%lexer"
NAME ::= "%name"
RIGHT ::= "%right"
START::= "%start"
TERM ::= "%token"
TERM::= "%term"
TYPE ::= "%type"
TYPE ::= "%symbol"
UNION ::= ("%union"|"%stack"|"%class"|"%struct")
PREC ::= "%prec"
```
